# permissions for end users to view models.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-viewer-role
rules:
- apiGroups:
  - model.distributed.io
  resources:
  - models
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - model.distributed.io
  resources:
  - models/status
  verbs:
  - get
