# permissions for end users to view torchjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: torchjob-viewer-role
rules:
- apiGroups:
  - train.distributed.io
  resources:
  - torchjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - train.distributed.io
  resources:
  - torchjobs/status
  verbs:
  - get
