/*
Copyright 2023 Hailiang Zhao.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// ProjectPrefix is the global prefix。
const ProjectPrefix = "distributed.io"

const (
	// EnvModelPath is the env key to indicate model path in container.
	EnvModelPath = "TORCH_ON_K8S_MODEL_PATH"

	// DefaultModelPathInImage is the default path where model artifacts are stored inside the model image generated by Kaniko.
	DefaultModelPathInImage = "/torch-on-k8s-model"
)

/* Local storage related. The following labels are used when local storage mode is chosen for model saving. */

type NodeStorageType string

const (
	LabelNodeStorageType     = ProjectPrefix + "/storage-type"
	LabelNodeStorageTypeFast = "fast"
)
