/*
Copyright 2023 Hailiang Zhao.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hliangzhao/torch-on-k8s/apis/train/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTorchJobs implements TorchJobInterface
type FakeTorchJobs struct {
	Fake *FakeTrainV1alpha1
	ns   string
}

var torchjobsResource = schema.GroupVersionResource{Group: "train.distributed.io", Version: "v1alpha1", Resource: "torchjobs"}

var torchjobsKind = schema.GroupVersionKind{Group: "train.distributed.io", Version: "v1alpha1", Kind: "TorchJob"}

// Get takes name of the torchJob, and returns the corresponding torchJob object, and an error if there is any.
func (c *FakeTorchJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TorchJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(torchjobsResource, c.ns, name), &v1alpha1.TorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TorchJob), err
}

// List takes label and field selectors, and returns the list of TorchJobs that match those selectors.
func (c *FakeTorchJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TorchJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(torchjobsResource, torchjobsKind, c.ns, opts), &v1alpha1.TorchJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TorchJobList{ListMeta: obj.(*v1alpha1.TorchJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.TorchJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested torchJobs.
func (c *FakeTorchJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(torchjobsResource, c.ns, opts))

}

// Create takes the representation of a torchJob and creates it.  Returns the server's representation of the torchJob, and an error, if there is any.
func (c *FakeTorchJobs) Create(ctx context.Context, torchJob *v1alpha1.TorchJob, opts v1.CreateOptions) (result *v1alpha1.TorchJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(torchjobsResource, c.ns, torchJob), &v1alpha1.TorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TorchJob), err
}

// Update takes the representation of a torchJob and updates it. Returns the server's representation of the torchJob, and an error, if there is any.
func (c *FakeTorchJobs) Update(ctx context.Context, torchJob *v1alpha1.TorchJob, opts v1.UpdateOptions) (result *v1alpha1.TorchJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(torchjobsResource, c.ns, torchJob), &v1alpha1.TorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TorchJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTorchJobs) UpdateStatus(ctx context.Context, torchJob *v1alpha1.TorchJob, opts v1.UpdateOptions) (*v1alpha1.TorchJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(torchjobsResource, "status", c.ns, torchJob), &v1alpha1.TorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TorchJob), err
}

// Delete takes name of the torchJob and deletes it. Returns an error if one occurs.
func (c *FakeTorchJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(torchjobsResource, c.ns, name), &v1alpha1.TorchJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTorchJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(torchjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TorchJobList{})
	return err
}

// Patch applies the patch and returns the patched torchJob.
func (c *FakeTorchJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TorchJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(torchjobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TorchJob), err
}
